/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AlterarVaca.java
 *
 * Created on 04/12/2009, 20:36:22
 */

package projeto.gui;

import projeto.afazenda.Vaca;
import projeto.bd.VacasDAO;
import projeto.afazenda.Vaqueiro;
import projeto.bd.VaqueirosDAO;
import projeto.afazenda.Rebanho;
import projeto.bd.RebanhoDAO;
import java.util.List;

/**
 *
 * @author Rodolfo
 */
public class AlterarVaca extends javax.swing.JFrame {

    CrudVacas crudVacas;
    VacasDAO vacasDAO = new VacasDAO();
    VaqueirosDAO vaqueirosDAO = new VaqueirosDAO();
    RebanhoDAO rebanhoDAO = new RebanhoDAO();
    int vacaID;
    /** Creates new form AlterarVaca */
    public AlterarVaca(CrudVacas crudVacas, boolean visivel) {
        setVisible(visivel);
        setTitle("A Fazenda - Alterar Vaca");
        setBounds(new java.awt.Rectangle(300, 180, 600, 600));
        this.crudVacas = crudVacas;
        initComponents();
        atualizarListaVaqueiros();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        listaVacas = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        listaVaqueiros = new javax.swing.JComboBox();
        confirmar = new javax.swing.JButton();
        voltar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        listaRebanhos = new javax.swing.JComboBox();
        mensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel1.setText("Alterar Vaca");

        jLabel2.setText("Vaca:");

        jLabel3.setText("Nome:");

        jLabel4.setText("Idade:");

        jLabel5.setText("Quantidade de Filhos:");

        jLabel6.setText("Vaqueiro Responsavel:");

        listaVacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaVacasActionPerformed(evt);
            }
        });

        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        jLabel7.setText("Rebanho:");

        mensagem.setForeground(new java.awt.Color(255, 0, 0));
        mensagem.setText("mensagem");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel1)
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(confirmar)
                        .addGap(18, 18, 18)
                        .addComponent(voltar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(listaVaqueiros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1)
                        .addComponent(jTextField2)
                        .addComponent(jTextField3)
                        .addComponent(listaVacas, 0, 266, Short.MAX_VALUE)
                        .addComponent(listaRebanhos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(mensagem)
                .addContainerGap(200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(listaVacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(listaVaqueiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(listaRebanhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmar)
                    .addComponent(voltar))
                .addGap(18, 18, 18)
                .addComponent(mensagem)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        mensagem.setVisible(false);
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        mensagem.setVisible(false);
        setVisible(false);
        crudVacas.setVisible(true);
}//GEN-LAST:event_voltarActionPerformed

    private void listaVacasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaVacasActionPerformed

        int indice = listaVacas.getSelectedIndex();
        //mini-gambiarra para evitar que indice seja -1 ;D
        if (indice == -1) {
            indice = 0;
        }
        
        vacaID = getVacaID(indice);

        
        jTextField1.setText(vacasDAO.getNomeVaca(vacaID));
        jTextField2.setText(String.valueOf(vacasDAO.getIdadeVaca(vacaID)));
        jTextField3.setText(String.valueOf(vacasDAO.getQtdeFilho(vacaID)));


    }//GEN-LAST:event_listaVacasActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        vacasDAO.atualizaNome(jTextField1.getText(), vacaID);
        vacasDAO.atualizaIdade(Integer.parseInt(jTextField2.getText()), vacaID);
        vacasDAO.atualizaQntdDeFIlhos(Integer.parseInt(jTextField3.getText()), vacaID);
        vacasDAO.atualizaRebanho(getIDRebanhoSelecionado(), vacaID);
        vacasDAO.atualizaVaqueiro(getCPFVaqueiroSelecionado(), vacaID);
        mensagem.setText("Dados alterados com sucesso!");
        mensagem.setVisible(true);
    }//GEN-LAST:event_confirmarActionPerformed

    private String getCPFVaqueiroSelecionado() {
        return listaVaqueiros.getSelectedItem().toString().substring(0, 11);
    }
    
    private int getRebanhoID(int indice){
        List<Rebanho> listaRebanhosTemp = rebanhoDAO.getTodosRebanhos();
        int rebanhoID = listaRebanhosTemp.get(indice).getID();
        return rebanhoID;
    }
    
    private int getIDRebanhoSelecionado() {
        int rebanhoID = 0;
        if (listaRebanhos.getSelectedItem().toString() != null) {
            int indice = listaRebanhos.getSelectedIndex();
            //mini-gambiarra para evitar que indice seja -1 ;D
            if (indice == -1) {
                indice = 0;
            }
            rebanhoID = getRebanhoID(indice);
        }
       
        return rebanhoID;
    }

    public void atualizaListaVacas(int rebanhoID) {
        listaVacas.removeAllItems();
        for(Vaca vaca : vacasDAO.getTodasVacas(rebanhoID)) {
            listaVacas.addItem("" + vaca.getID() + " - " + vaca.getNome());
        }
    }

    public void atualizarListaVaqueiros(){
        listaVaqueiros.removeAllItems();
    	for(Vaqueiro vaq: vaqueirosDAO.getTodosVaqueiros()) {
            listaVaqueiros.addItem(vaq.getCpf() + " - " + vaq.getNome());
        }
    }

    public void atualizarListaRebanhos() {
    	listaRebanhos.removeAllItems();
    	for(Rebanho reb: rebanhoDAO.getTodosRebanhos()) {
            listaRebanhos.addItem("" + reb.getID() + " - " + reb.getNome());
        }

    }
    private int getVacaID(int indice){
        List<Vaca> listaVacasTemp = vacasDAO.getTodasVacas(crudVacas.rebanhoID);
        int vacaID = listaVacasTemp.get(indice).getID();
        return vacaID;

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JComboBox listaRebanhos;
    private javax.swing.JComboBox listaVacas;
    private javax.swing.JComboBox listaVaqueiros;
    javax.swing.JLabel mensagem;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables

}
