/*
 * To change this template, choose Tools | Templates.
 * and open the template in the editor.
 */

/*
 * MenuInicial.java
 *
 * Created on 07/11/2009, 18:49:35
 */

package projeto.gui;

/**
 *
 * @author Rodolfo
 */
public class Main extends javax.swing.JFrame {

    CadastrarRebanho cadastradorRebanho = new CadastrarRebanho(this, false);
    GerenciarRebanhos gerenciadorDeRebanhos = new GerenciarRebanhos(this, false);
    VacinarVacas vacinadorDeVacas = new VacinarVacas(this, false);
    CoberturaDeVacas telaCoberturaDeVacas = new CoberturaDeVacas(this, false);
    Tiragens menuTiragens = new Tiragens(this, false);
    
    
    /** Creates new form MenuInicial */
    public Main() {

        setBounds(new java.awt.Rectangle(350, 180, 800, 800));
        setTitle("A Fazenda");
        
        initComponents();
               
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        figura = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cadastrarRebanho = new javax.swing.JButton();
        gerenciarRebanhos = new javax.swing.JButton();
        vacinarVacas = new javax.swing.JButton();
        coberturaDeVacas = new javax.swing.JButton();
        tiragens = new javax.swing.JButton();
        gerenciarVendas = new javax.swing.JButton();
        gerenciarClientes = new javax.swing.JButton();
        caixa = new javax.swing.JButton();
        sair = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        boasVindas = new javax.swing.JLabel();
        vacaFalando = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("A Fazenda");

        titulo.setFont(new java.awt.Font("Tahoma", 1, 14));
        titulo.setText("A Fazenda");
        
//        figura.setIcon(new javax.swing.ImageIcon("vacaPlanoFundo.jpg")); // NOI18N
//        figura.setText("figura");
//        figura.setBounds(400, 250, 0, 0);
        
        cadastrarRebanho.setText("CADASTRAR REBANHO");
        cadastrarRebanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarRebanhoActionPerformed(evt);
            }
        });

        gerenciarRebanhos.setText("GERENCIAR REBANHOS");
        gerenciarRebanhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerenciarRebanhosActionPerformed(evt);
            }
        });

        vacinarVacas.setText("VACINAR VACAS");
        vacinarVacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vacinarVacasActionPerformed(evt);
            }
        });

        coberturaDeVacas.setText("COBERTURA DE VACAS");
        coberturaDeVacas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coberturaDeVacasActionPerformed(evt);
            }
        });

        tiragens.setText("TIRAGENS");
        tiragens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiragensActionPerformed(evt);
            }
        });

        gerenciarVendas.setText("GERENCIAR VENDAS");

        gerenciarClientes.setText("GERENCIAR CLIENTES");

        caixa.setText("CAIXA");
        caixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaActionPerformed(evt);
            }
        });

        sair.setText("SAIR");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        boasVindas.setFont(new java.awt.Font("Tahoma", 1, 24));
        boasVindas.setText("Seja bem vindo!");

        vacaFalando.setFont(new java.awt.Font("Tahoma", 1, 48));
        vacaFalando.setText("MUUUUUUU!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(caixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gerenciarClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gerenciarVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tiragens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coberturaDeVacas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vacinarVacas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                    .addComponent(figura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gerenciarRebanhos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cadastrarRebanho, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(boasVindas)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(vacaFalando)
                        .addGap(29, 29, 29))))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(230, 230, 230))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cadastrarRebanho)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gerenciarRebanhos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vacinarVacas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(coberturaDeVacas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tiragens)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gerenciarVendas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gerenciarClientes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(caixa)
                                .addGap(26, 26, 26)
                                .addComponent(sair))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(boasVindas)
                        .addGap(50, 50, 50)
                        .addComponent(vacaFalando)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void cadastrarRebanhoActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        cadastradorRebanho.setVisible(true);
        setVisible(false);
}                                                

    private void gerenciarRebanhosActionPerformed(java.awt.event.ActionEvent evt) {
        gerenciadorDeRebanhos.setVisible(true);
        setVisible(false);
    }

    private void vacinarVacasActionPerformed(java.awt.event.ActionEvent evt) {
        vacinadorDeVacas.setVisible(true);
        setVisible(false);
    }

    private void coberturaDeVacasActionPerformed(java.awt.event.ActionEvent evt) {
        telaCoberturaDeVacas.setVisible(true);
        setVisible(false);
    }

    private void tiragensActionPerformed(java.awt.event.ActionEvent evt) {
        menuTiragens.setVisible(true);
        setVisible(false);
    }
    
    private void caixaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO: man-generated method stub ;D
    }

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel boasVindas;
    private javax.swing.JButton cadastrarRebanho;
    private javax.swing.JButton caixa;
    private javax.swing.JButton coberturaDeVacas;
    private javax.swing.JButton gerenciarClientes;
    private javax.swing.JButton gerenciarRebanhos;
    private javax.swing.JButton gerenciarVendas;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton sair;
    private javax.swing.JButton tiragens;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel figura;
    private javax.swing.JLabel vacaFalando;
    private javax.swing.JButton vacinarVacas;
    // End of variables declaration

}
