/*
 * To change this template, choose Tools | Templates.
 * and open the template in the editor.
 */

/*
 * Tiragens.java
 *
 * Created on 27/11/2009, 23:49:12
 */

package projeto.gui;

/**
 *
 * @author Rodolfo
 */
public class Tiragens extends javax.swing.JFrame {
    Main menu;
    NovaTiragem menuNovaTiragem = new NovaTiragem(this, false);

    /** Creates new form Tiragens */
    public Tiragens(Main menu, boolean visivel) {
        this.menu = menu;
        setBounds(new java.awt.Rectangle(350,180,800,800));
        setVisible(visivel);
        setTitle("A Fazenda - Tiragens");
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        novaTiragem = new javax.swing.JButton();
        gerenciarTiragens = new javax.swing.JButton();
        voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        titulo.setText("Tiragens");

        novaTiragem.setText("Nova tiragem de leite");
        novaTiragem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaTiragemActionPerformed(evt);
            }
        });

        gerenciarTiragens.setText("Gerenciar tiragens feitas");

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(titulo)
                .addContainerGap(139, Short.MAX_VALUE))
            .addComponent(separador, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(novaTiragem, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gerenciarTiragens, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(voltar, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(novaTiragem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gerenciarTiragens)
                .addGap(18, 18, 18)
                .addComponent(voltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_voltarActionPerformed

    private void novaTiragemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaTiragemActionPerformed
        setVisible(false);
        menuNovaTiragem.setVisible(true);
    }//GEN-LAST:event_novaTiragemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gerenciarTiragens;
    private javax.swing.JButton novaTiragem;
    private javax.swing.JSeparator separador;
    private javax.swing.JLabel titulo;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables

}
