/*
 * To change this template, choose Tools | Templates.
 * and open the template in the editor.
 */

/*
 * CoberturaDeVacas.java
 *
 * Created on 08/11/2009, 22:59:22
 */

package projeto.gui;

/**
 *
 * @author Rodolfo
 */
public class CoberturaDeVacas extends javax.swing.JFrame {

    Main menu;
    Inseminar inseminador = new Inseminar(this, false);
    /** Creates new form CoberturaDeVacas */
    public CoberturaDeVacas(Main menu, boolean visivel) {
       setVisible(visivel);
       setTitle("A Fazenda - Cobertura de Vacas");
       setBounds(new java.awt.Rectangle(300,200,600,600));
        this.menu = menu;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        inseminar = new javax.swing.JButton();
        coberturas = new javax.swing.JButton();
        coberturasPorDataInseminacao = new javax.swing.JButton();
        coberturasPorDataParto = new javax.swing.JButton();
        coberturasPorTouroInseminador = new javax.swing.JButton();
        voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titulo.setText("Cobertura de Vacas");

        inseminar.setText("Inseminar Vaca");
        inseminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inseminarActionPerformed(evt);
            }
        });

        coberturas.setText("Coberturas");

        coberturasPorDataInseminacao.setText("Coberturas por data de inseminacao");

        coberturasPorDataParto.setText("Coberturas por data de parto");

        coberturasPorTouroInseminador.setText("Coberturas por touro");
        coberturasPorTouroInseminador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coberturasPorTouroInseminadorActionPerformed(evt);
            }
        });

        voltar.setText("Voltar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(131, 131, 131))
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(voltar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coberturasPorTouroInseminador, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coberturasPorDataParto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coberturasPorDataInseminacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coberturas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inseminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {coberturas, coberturasPorDataInseminacao, coberturasPorDataParto, coberturasPorTouroInseminador, inseminar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inseminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coberturas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coberturasPorDataInseminacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coberturasPorDataParto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(coberturasPorTouroInseminador)
                .addGap(18, 18, 18)
                .addComponent(voltar)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void coberturasPorTouroInseminadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coberturasPorTouroInseminadorActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_coberturasPorTouroInseminadorActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        setVisible(false);
        menu.setVisible(true);
}//GEN-LAST:event_voltarActionPerformed

    private void inseminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inseminarActionPerformed
        inseminador.setVisible(true);
        setVisible(false);
}//GEN-LAST:event_inseminarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton coberturas;
    private javax.swing.JButton coberturasPorDataInseminacao;
    private javax.swing.JButton coberturasPorDataParto;
    private javax.swing.JButton coberturasPorTouroInseminador;
    private javax.swing.JButton inseminar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel titulo;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables

}
