/*
 * To change this template, choose Tools | Templates.
 * and open the template in the editor.
 */

/*
 * NovaTiragem.java
 *
 * Created on 28/11/2009, 00:10:59
 */

package projeto.gui;

import java.util.List;

import projeto.afazenda.Rebanho;
import projeto.afazenda.Vaca;
import projeto.bd.RebanhoDAO;
import projeto.bd.VacasDAO;

/**
 *
 * @author Rodolfo
 */
public class NovaTiragem extends javax.swing.JFrame {

    Tiragens menuTiragens;
    VacasDAO vacasDAO = new VacasDAO();
    RebanhoDAO rebanhoDAO = new RebanhoDAO();
    /** Creates new form NovaTiragem */
    public NovaTiragem(Tiragens menuTiragens, boolean visivel) {
        this.menuTiragens = menuTiragens;
        setTitle("A Fazenda - Nova Tiragem");
        setVisible(visivel);
        setBounds(new java.awt.Rectangle(350, 180, 800, 800));
        initComponents();
        atualizarListaRebanhos();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agrupadorDeRadioButtons = new javax.swing.ButtonGroup();
        titulo = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        tiragemMatinal = new javax.swing.JRadioButton();
        tiragemVespertina = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        listaRebanhos = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        listaVacas = new javax.swing.JComboBox();
        botaoProximo = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titulo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        titulo.setText("Nova Tiragem");

        jLabel1.setText("Tipo:");

        agrupadorDeRadioButtons.add(tiragemMatinal);
        tiragemMatinal.setText("Manha");

        agrupadorDeRadioButtons.add(tiragemVespertina);
        tiragemVespertina.setText("Tarde");

        jLabel2.setText("Data (dd/mm/aaaa):");

        jLabel3.setText("Rebanho:");

        listaRebanhos.setModel(new javax.swing.DefaultComboBoxModel());
        listaRebanhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaRebanhosActionPerformed(evt);
            }
        });

        jLabel4.setText("Vaca:");

        listaVacas.setModel(new javax.swing.DefaultComboBoxModel());

        botaoProximo.setText("Proximo");

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(titulo))
            .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(tiragemMatinal)
                        .addGap(18, 18, 18)
                        .addComponent(tiragemVespertina))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoProximo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoCancelar))
                    .addComponent(listaVacas, 0, 209, Short.MAX_VALUE)
                    .addComponent(listaRebanhos, 0, 209, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tiragemMatinal)
                    .addComponent(tiragemVespertina))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(listaRebanhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(listaVacas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoProximo)
                    .addComponent(botaoCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        setVisible(false);
        menuTiragens.setVisible(true);
    }//GEN-LAST:event_botaoCancelarActionPerformed
    
    public void atualizarListaRebanhos() {
     	listaRebanhos.removeAllItems();
       	for(Rebanho reb: rebanhoDAO.getTodosRebanhos()) {
            listaRebanhos.addItem("" + reb.getID() + " - " + reb.getNome());
        }
    }
    
    private void listaRebanhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaRebanhosActionPerformed
        int indice = listaRebanhos.getSelectedIndex();
        //mini-gambiarra para evitar que indice seja -1 ;D
        if (indice == -1) {
        	indice = 0;
        }
        List<Rebanho> listaRebanhosTemp = rebanhoDAO.getTodosRebanhos();
        int rebanhoID = listaRebanhosTemp.get(indice).getID();
        atualizarListaVacas(rebanhoID);
    }
    
    public void atualizarListaVacas(int rebanhoID) {
        listaVacas.removeAllItems();
        for(Vaca vaca : vacasDAO.getTodasVacas(rebanhoID)) {
            listaVacas.addItem("" + vaca.getID() + " - " + vaca.getNome());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup agrupadorDeRadioButtons;
    private javax.swing.JButton botaoProximo;
    private javax.swing.JButton botaoCancelar;
    javax.swing.JComboBox listaRebanhos;
    javax.swing.JComboBox listaVacas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton tiragemMatinal;
    private javax.swing.JRadioButton tiragemVespertina;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JSeparator separador;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables

}
